# Generated by Django 5.1.3 on 2024-12-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('clerkuserid', models.UUIDField(db_column='ClerkUserID', unique=True)),
                ('email', models.CharField(db_column='Email', max_length=255, unique=True)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('lastname', models.CharField(db_column='LastName', max_length=50)),
            ],
            options={
                'db_table': 'UserAccount',
                'managed': False,
            },
        ),
    ]
